name: Commitlint
description: Lint commit messages for compliance with Angular convention 

runs:
  using: "composite"
  steps:
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          commitlint.config.js
          node_modules
          package-lock.json
          package.json
        key: commitlint-${{hashFiles('.github/actions/commitlint/action.yaml')}}
        restore-keys: commitlint-

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm install --save-dev @commitlint/cli @commitlint/config-angular
        echo "module.exports = {extends: ['@commitlint/config-angular']};" > commitlint.config.js

    - name: Validate all commits from PR
      shell: bash
      run: npx commitlint --from ${{github.event.pull_request.base.sha}} --to ${{github.event.pull_request.head.sha}} --verbose
