name: ci-cd

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  commitlint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Check-out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commitlint
        uses: ./.github/actions/commitlint

  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Pytest
        uses: ./.github/actions/pytest
        with:
          package-name: pyname
          python-version: "3.10"
          poetry-version: 1.3.1
          min-cov: 0
          retention-days: 10

  release:
    needs: pytest
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Check-out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'master'

      - name: Release
        uses: ./.github/actions/release
        with:
          token: ${{secrets.GH_TOKEN}}
          python-version: "3.10"
          poetry-version: 1.3.1
